version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: niivi_challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data.csv:/data/my_file.csv 
  schema-generator:
    image: postgres:15-alpine
    container_name: schema-generator
    depends_on:
      - postgres
    volumes:
      - shared-schema:/shared
    environment:
      PGPASSWORD: password
    entrypoint: >
      sh -c "
        until pg_isready -h postgres -p 5432 -U postgres; do sleep 1; done;
        pg_dump -h postgres -U postgres -d niivi_challenge --schema-only > /shared/schema.sql;
      "
  
  # API Gateway
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/niivi_challenge
    depends_on:
      - postgres
    volumes:
      - ./services/api-gateway:/app


  # Model Service
  model-service:
    build: ./services/model
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/niivi_challenge
      - OLLAMA_HOST=http://ollama:11434
      - SCHEMA_FILE_PATH=/app/schema/schema.sql
    depends_on:
      ollama:
        condition: service_started
      # 2. Tu condición de completado para el extractor de esquema
      schema-generator:
        condition: service_completed_successfully
    volumes:
      - ./services/model:/app
      - shared-schema:/app/schema:ro # Monta el esquema como Solo Lectura
      

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434  # <-- CRÍTICO: Le dice a Ollama que acepte conexiones externas (de otros contenedores)
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped


  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NODE_ENV=production
    depends_on:
      - api-gateway

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - api-gateway

volumes:
  postgres_data:
  ollama-data:
  shared-schema:
